services:
  # Neon Local Database Proxy for Development
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: devops-neon-local-dev
    ports:
      - '5432:5432'
    env_file:
      - ./.env.development
    networks:
      - app-network
    restart: unless-stopped

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-app-dev
    ports:
      - '5000:5000'
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - neon-local
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev

networks:
  app-network:
    driver: bridge
