name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          echo "::notice::Running ESLint to check code quality..."
          if ! npm run lint; then
            echo "::error::ESLint found issues. Run 'npm run lint:fix' to fix automatically fixable problems."
            exit 1
          fi
          echo "::notice::✅ ESLint passed successfully!"

      - name: Check Prettier formatting
        run: |
          echo "::notice::Checking code formatting with Prettier..."
          if ! npm run format:check; then
            echo "::error::Code formatting issues found. Run 'npm run format' to fix formatting."
            exit 1
          fi
          echo "::notice::✅ Prettier formatting check passed!"

      - name: Annotate success
        if: success()
        run: |
          echo "::notice::🎉 All linting and formatting checks passed successfully!"
          echo "Code quality standards are maintained."
